# Generated by Django 5.0.6 on 2024-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_condation'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('title3', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('banar', models.ImageField(upload_to='offer_images/')),
            ],
        ),
    ]
