# Generated by Django 5.0.6 on 2024-07-01 12:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_new_price_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=19, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=19, verbose_name='Amount'),
        ),
    ]
