# Generated by Django 5.0.6 on 2024-07-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_new_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
