# Generated by Django 5.0.6 on 2024-06-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
