# Generated by Django 5.0.6 on 2024-06-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('title3', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_descripts', models.CharField(blank=True, max_length=255, null=True)),
                ('product_slug', models.CharField(max_length=255)),
            ],
        ),
    ]
