# Generated by Django 5.0.6 on 2024-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_Featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_New_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_Popular',
            field=models.BooleanField(default=False),
        ),
    ]
