# Generated by Django 5.0.6 on 2024-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider_is_featured_slider_is_new_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='is_Featured',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_New_added',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_Popular',
        ),
    ]
